sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 149059
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tHJPpj78PXr32MhcnEt
    access-key-secret: n6sZtbhSKNM6jJWc8VA6jNOzU6byNm
    bucket-name: sky-study-fie
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxe444c7cb1498bc63
    secret: 7632e61a22aca735607e540c07702674
    # 微信支付配置
#    mchid: 1561414331
#    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
#    privateKeyFilePath: D:\apiclient_key.pem
#    apiV3Key: CZBK51236435wxpay435434323FFDuv3
#    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
#    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
#    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php
